[features]
seeds = false
[programs.localnet]
chainlink_test = "F1j1twktTSRv1e5rGF5cA18eyhdW8fhherW6k9aPvChq"

[programs.devnet]
nft_marketplace = "F1j1twktTSRv1e5rGF5cA18eyhdW8fhherW6k9aPvChq"

[registry]
url = "https://anchor.projectserum.com"

#[provider]
#cluster = "localnet"
#wallet = "/home/alex/.config/solana/id.json"

[provider]
cluster = "devnet"
wallet = "/home/alex/blockchain/Keys/alex.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
